[package]
name = "mongo-commands"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { version = "2.0.1", features = ["bson-chrono-0_4", "bson-uuid-0_8"] }
tokio = "1.12"
serde_json = "1.0"